// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var Note, lastId, note1, note2, note3, note4;

    lastId = null;
    Note = (function() {
      var el;

      Note.prototype.id = null;

      Note.prototype.pos = {
        top: 100,
        left: 20
      };

      Note.prototype.size = {
        width: 200,
        height: 100
      };

      Note.prototype.text = "Lorem ipsum dolor sit amet";

      el = null;

      function Note(options) {
        var key, value;

        if (options) {
          for (key in options) {
            value = options[key];
            if (key in this) {
              this[key] = value;
            }
          }
          console.log(this.size);
        }
      }

      Note.prototype.insert = function(container) {
        var _this = this;

        this.container = $(container);
        if (this.id === null) {
          this.newId;
          return;
        }
        this.$el = $("<div class=\"note ui-widget-content\" id=\"note" + this.id + "\">				<!-- h3 class=\"ui-widget-header\">Notes</h3 --><textarea>" + this.text + "</textarea></div>");
        this.container.append(this.$el);
        this._setPosition();
        this._setSize();
        this.$el.draggable({
          stack: '.note',
          stop: function(event, ui) {
            return _this.save("pos");
          }
        });
        this.$el.resizable({
          stop: function(event, ui) {
            return _this.save("size");
          }
        });
        this.save("pos");
        this.save("size");
        this.save("text");
      };

      Note.prototype.save = function(what) {
        var reqString;

        reqString = {
          "id": "note" + this.id,
          "action": "save"
        };
        reqString[what] = this[what];
        console.log(reqString);
        return $.post("./ajax.php", reqString, function(data) {
          return console.log(data);
        });
      };

      Note.prototype.newId = function() {
        var _this = this;

        if (lastId) {
          lastId = lastId + 1;
          return lastId;
        } else {

        }
        return $.get("./ajax.php", {
          action: "newId"
        }, function(data) {
          _this.setId(data);
          return _this.insert(_this.container);
        }, "json");
      };

      Note.prototype.setId = function(data) {
        this.id = data['id'];
        return lastId = data['id'];
      };

      Note.prototype._setPosition = function() {
        return this.$el.offset(this.pos);
      };

      Note.prototype._setSize = function() {
        this.$el.width(this.size.width);
        return this.$el.height(this.size.height);
      };

      return Note;

    })();
    note1 = new Note({
      id: null,
      size: {
        width: 900,
        height: 400
      }
    });
    note2 = new Note({
      id: null,
      bla: "test",
      pos: {
        top: 150,
        left: 300
      },
      size: {
        width: 400,
        height: 200
      },
      text: "Lorem ipsum dolor sit amet"
    });
    note3 = new Note({
      id: null,
      pos: {
        top: 200,
        left: 220
      },
      size: {
        width: 200,
        height: 700
      },
      text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime, est neque minima? Cum, alias, fuga ipsum modi doloribus deserunt libero veritatis numquam voluptatibus ut nulla exercitationem dolores placeat rerum dolor."
    });
    note4 = new Note({
      id: null,
      pos: {
        top: 180,
        left: 50
      },
      size: {
        width: 200,
        height: 200
      },
      text: "Lorem ipsum dolor sit amet"
    });
    note1.insert("#container");
    note2.insert("#container");
    note3.insert("#container");
    return note4.insert("#container");
  });

}).call(this);
