// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var Note, note;

    Note = (function() {
      var el;

      Note.prototype.id = 1;

      Note.prototype.pos = {
        top: 100,
        left: 20
      };

      Note.prototype.size = {
        width: 200,
        height: 100
      };

      Note.prototype.text = "Lorem ipsum dolor sit amet";

      el = null;

      function Note(options) {
        if (options) {
          console.log(options);
          this.id = options.id, this.pos = options.pos, this.size = options.size, this.text = options.text;
          console.log(this.size);
        }
      }

      Note.prototype.insert = function(container) {
        var _this = this;

        this.container = $(container);
        this.$el = $("<div class=\"note ui-widget-content\" id=\"note" + this.id + "\">				<!-- h3 class=\"ui-widget-header\">Notes</h3 --><textarea>" + this.text + "</textarea></div>");
        this.container.append(this.$el);
        this._setPosition();
        this._setSize();
        this.$el.draggable({
          stack: this.$el,
          stop: function(event, ui) {
            return _this.save("pos");
          }
        });
        this.$el.resizable({
          stop: function(event, ui) {
            return _this.save("size");
          }
        });
      };

      Note.prototype.save = function(what) {
        var reqString;

        reqString = {
          "id": "note" + this.id,
          "action": "save"
        };
        reqString[what] = this[what];
        return $.post("./ajax.php", reqString, function(data) {
          return console.log(data);
        });
      };

      Note.prototype._setPosition = function() {
        return this.$el.offset(this.pos);
      };

      Note.prototype._setSize = function() {
        this.$el.width(this.size.width);
        return this.$el.height(this.size.height);
      };

      return Note;

    })();
    note = new Note({
      id: 2,
      pos: {
        top: 100,
        left: 100
      },
      size: {
        width: 300,
        height: 300
      },
      text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime, fuga, vero, maiores, magni officia eius animi eum eveniet debitis blanditiis deserunt dolorum natus ab necessitatibus dolore fugit repellat ullam explicabo.'
    });
    return note.insert("#container");
  });

}).call(this);
